### ISSUE TITLE
Recommend some desktop clients that support Carbons

### ISSUE THREAD

**Issue by catern** [digicoop/kaiwa-site#1]
Message carbons are a fairly important feature for all clients to support. Pidgin does not support Message Carbons. Gajim does. Therefore you might consider recommending Gajim (possibly in addition to Pidgin), and/or some of the terminal clients that support carbons (profanity, mcabber).

**Comment by hellerbarde** [comment]
Currently, gajim is recommended, so maybe close this issue.
